language: julia
os:
  - osx
  - linux
julia:
  - 1.1
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'import Pkg; Pkg.clone(pwd());'
#   - julia -e 'import Pkg; Pkg.build("DocumentFunction"); Pkg.test("DocumentFunction"; coverage=true)'
after_success:
  - julia -e 'import Pkg; import DocumentFunction; cd(joinpath(dirname(pathof(DocumentFunction)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
